### ISSUE TITLE
How to reproduce the results in the paper

### ISSUE THREAD

**Issue by zll666** [freesunshine0316/nary-grn#11]
hello, I did a 5 cross-validation with your code, but the test set's accurate was only 77% . Will the parameters in the config file still need to be adjusted? I am confused how I can reproduce the results 83%.

**Comment by freesunshine0316** [comment]
Hi @zll666 

Just checked the config file. You need to change the value of "class_num" to 2. The value can be either 5 or 2, meaning "multi-class classification" and "binary classification", respectively.

**Comment by freesunshine0316** [comment]
@zll666 Just update the repository a little bit.
