### ISSUE TITLE
How to configure the environment？

### ISSUE THREAD

**Issue by ysn7** [freesunshine0316/nary-grn#15]
My environment is python3.6,cuda 10.0,cudnn 7.4, can you tell me the detail settings about python 2,such as tensorflow and python's version?

**Comment by VV1266** [comment]
Tensorflow==1.10.0
Python 2.7

**Comment by ysn7** [comment]
> Tensorflow==1.10.0
> Python 2.7

thanks

**Comment by freesunshine0316** [comment]
> Tensorflow==1.10.0
> Python 2.7

Thanks

**Comment by freesunshine0316** [comment]
Thanks @VV1266 
I think a higher version such as 1.14 may also work

**Comment by ysn7** [comment]
> Thanks @VV1266
> I think a higher version such as 1.14 may also work

Ok,thanks.I will try.
