### ISSUE TITLE
How to change to single sentence setting?

### ISSUE THREAD

**Issue by CHELSEA234** [freesunshine0316/nary-grn#7]
Hi @freesunshine0316,

Thanks you for sharing the code. I have successfully run it, but according to it (in the folder gs_lstm), I think the experiments have been done on Cross sentence setting for drug-gene-mutation. Can you tell me how to do experiments on Single sentence setting? Specifically, all instances in the one single sentence, as shown in the Table 3 in the paper.

Best

**Comment by freesunshine0316** [comment]
Hi @CHELSEA234 
Thank you being interested in our work. You can simply set "only_single_sent" to false for the single-sentence setting.

**Comment by freesunshine0316** [comment]
@CHELSEA234 Sorry there is an obvious mistake in my previous reply. I've modified it....

**Comment by CHELSEA234** [comment]
Thanks for your reply and help. 

I will try your suggestion later. Please let me temporarily close this issue. 

Thanks again.

**Comment by leslie991123** [comment]
> 嗨，
> 
> 感谢您分享代码。我已经成功运行了它，但根据它（在文件夹gs_lstm中），我认为实验是在药物基因突变的交叉句子设置上完成的。你能告诉我如何做单句设置的实验吗？具体来说，所有实例都在一个句子中，如论文中的表3所示。
> 
> 最好

可以分享一下具体如何运行的吗，我尝试了很多次还是不行，方便添加您的邮箱请教一下吗
