### ISSUE TITLE
Problem in understanding the data

### ISSUE THREAD

**Issue by nayakt** [freesunshine0316/nary-grn#8]
I have some problem in understanding the data. What will be the value of <ANNO_TYPE_variant>, <ANNO_TYPE_drug> and <ANNO_TYPE_gene> in following example. Thanks in advance !!!!

The <ANNO_TYPE_variant> mutation results in alteration of the topology of the ATP binding pocket not only interrupting the physicochemical binding of <ANNO_TYPE_drug> , but also leading to much increased affinity of the <ANNO_TYPE_gene> protein to ATP resulting in resistance to EGFR-TKIs [ ] .	21	32	1	resistance or non-response

**Comment by freesunshine0316** [comment]
Sorry I don't understand. 

Oh, you may use a wrong file. This looks like a marked version of the original file.

**Comment by nayakt** [comment]
I am talking about the 'sentences_2nd' file in your repository.

**Comment by freesunshine0316** [comment]
Hi, You need to use the ones with names like "sentence_graph_1" and "sentence_graph_2"

**Comment by nayakt** [comment]
did you mean 'data_graph_1' and 'data_graph_2' ?

**Comment by freesunshine0316** [comment]
Yes, they should be the correct files.

**Comment by nayakt** [comment]
OK. Thanks !!!!

**Comment by VV8** [comment]
Hey freesunshine0316, Can you explain to me, how the in every instance of data observation you created the "arc" feature from the dependency parser. **inst[u'sentences'][0][u'nodes'][9][u'arcs']** . It will be a great help if you can help me out for this.
